Fetch upstream
Add updates from MagiskOnWSA
Standalone policy update in Magisk v24.3 (no magiskpolicy fix)
Fix missing artifacts when downloading

diff --git a/.github/workflows/magisk.yml b/.github/workflows/magisk.yml
--- a/.github/workflows/magisk.yml
+++ b/.github/workflows/magisk.yml
@@ -112,9 +112,10 @@ jobs:
       - name: Dependencies
         run: |
           pip3 install beautifulsoup4 lxml
-          sudo apt-get update && sudo apt-get install setools lzip qemu-utils wine winetricks
-          wget -qO- "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/archive/$GITHUB_REF.tar.gz" | sudo tar --wildcards -zxvf- -C ~ --strip-component=2 '*/wine/*'
+          sudo apt-get update && sudo apt-get install setools lzip qemu-utils wine winetricks patchelf
+          wget -qO- "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/archive/$GITHUB_REF.tar.gz" | sudo tar --wildcards -zxvf- -C ~ --strip-component=2 '*/wine/*' '*/linker/*'
           winetricks msxml6
+          echo "163.172.251.201 store.rg-adguard.net" | sudo tee -a /etc/hosts
       - name: Download WSA
         shell: python
         run: |
@@ -224,15 +225,31 @@ jobs:
               info = zip.getinfo(name)
               info.filename = as_name
               zip.extract(info, dir)
-
+              
+          # changes to standalone_policy since v24.3
+          # extract_as(zip, f"lib/{ abi_map[arch][0] }/libmagiskinit.so", "magiskpolicy", "magisk")
+          # extract_as(zip, f"lib/{ abi_map['x64'][0] }/libmagiskinit.so", "magiskpolicy", ".")
+              
           with zipfile.ZipFile(out_file) as zip:
               extract_as(zip, f"lib/{ abi_map[arch][0] }/libmagisk64.so", "magisk64", "magisk")
               extract_as(zip, f"lib/{ abi_map[arch][1] }/libmagisk32.so", "magisk32", "magisk")
+              standalone_policy = False
+              try:
+                zip.getinfo(f"lib/{ abi_map[arch][0] }/libmagiskpolicy.so")
+                standalone_policy = True
+              except:
+                pass
               extract_as(zip, f"lib/{ abi_map[arch][0] }/libmagiskinit.so", "magiskinit", "magisk")
-              extract_as(zip, f"lib/{ abi_map[arch][0] }/libmagiskinit.so", "magiskpolicy", "magisk")
+              if standalone_policy:
+                extract_as(zip, f"lib/{ abi_map[arch][0] }/libmagiskpolicy.so", "magiskpolicy", "magisk")
+              else:
+                extract_as(zip, f"lib/{ abi_map[arch][0] }/libmagiskinit.so", "magiskpolicy", "magisk")
               extract_as(zip, f"lib/{ abi_map[arch][0] }/libmagiskboot.so", "magiskboot", "magisk")
               extract_as(zip, f"lib/{ abi_map[arch][0] }/libbusybox.so", "busybox", "magisk")
-              extract_as(zip, f"lib/{ abi_map['x64'][0] }/libmagiskinit.so", "magiskpolicy", ".")
+              if standalone_policy:
+                extract_as(zip, f"lib/{ abi_map['x64'][0] }/libmagiskpolicy.so", "magiskpolicy", ".")
+              else:
+                extract_as(zip, f"lib/{ abi_map['x64'][0] }/libmagiskinit.so", "magiskpolicy", ".")
               extract_as(zip, f"assets/boot_patch.sh", "boot_patch.sh", "magisk")
               extract_as(zip, f"assets/util_functions.sh", "util_functions.sh", "magisk")
       - name: Download OpenGApps
@@ -326,6 +343,12 @@ jobs:
           sudo find system/sbin -type f -exec chmod 0755 {} \;
           sudo find system/sbin -type f -exec chown root:root {} \;
           sudo find system/sbin -type f -exec chcon --reference system/product {} \;
+          # new since v24.3
+          sudo patchelf --replace-needed libc.so "${HOME}/libc.so" ./magiskpolicy || true
+          sudo patchelf --replace-needed libm.so "${HOME}/libm.so" ./magiskpolicy || true
+          sudo patchelf --replace-needed libdl.so "${HOME}/libdl.so" ./magiskpolicy || true
+          sudo patchelf --set-interpreter "${HOME}/linker64" ./magiskpolicy || true
+          # new since v24.3
           chmod +x ./magiskpolicy
           echo '/dev/magisk(/.*)?    u:object_r:magisk_file:s0' | sudo tee -a system/vendor/etc/selinux/vendor_file_contexts
           echo '/data/adb/magisk(/.*)?   u:object_r:magisk_file:s0' | sudo tee -a system/vendor/etc/selinux/vendor_file_contexts
@@ -599,6 +622,12 @@ jobs:
               exit
           }
 
+          if (((Test-Path -Path $(ls -Q ./${{ matrix.arch }} | paste -sd "," -)) -eq \$false).Count) {
+              Write-Error "Some files are missing in the zip. Please try to download it again from the browser downloader, or try to run the workflow again. Press any key to exist"
+              \$null = \$Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown')
+              exit 1
+          }
+          
           reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /t REG_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1"
 
           \$VMP = Get-WindowsOptionalFeature -Online -FeatureName 'VirtualMachinePlatform'
